"""add alert and settings tables

Revision ID: 73840b49aa17
Revises: a7570990d585
Create Date: 2026-09-23 12:26:20.937126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import table, column, String


# revision identifiers, used by Alembic.
revision: str = '73840b49aa17'
down_revision: Union[str, None] = 'a7570990d585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('alert_thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('bytes_threshold', sa.BigInteger(), nullable=False),
    sa.Column('notify_channel', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['pppoe_clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('threshold_id', sa.Integer(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accumulated_bytes_at_trigger', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['pppoe_clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['threshold_id'], ['alert_thresholds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    settings_table = table("settings", column("key", String), column("value", String))

    op.bulk_insert(
        settings_table,
        [
            {"key": "polling_interval_seconds", "value": "300"},
            {"key": "reset_day_of_month", "value": "1"},
            {"key": "retention_days", "value": "90"},
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_events')
    op.drop_table('alert_thresholds')
    op.drop_table('settings')
    # ### end Alembic commands ###
