"""add traffic_samples and accumulation_periods tables

Revision ID: a7570990d585
Revises: c8aced5619c2
Create Date: 2026-09-23 12:25:50.539066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7570990d585'
down_revision: Union[str, None] = 'c8aced5619c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traffic_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('sampled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rx_bytes_delta', sa.BigInteger(), nullable=False),
    sa.Column('tx_bytes_delta', sa.BigInteger(), nullable=False),
    sa.Column('rx_bps', sa.BigInteger(), nullable=False),
    sa.Column('tx_bps', sa.BigInteger(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['pppoe_clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_traffic_samples_client_time', 'traffic_samples', ['client_id', 'sampled_at'], unique=False)
    op.create_table('accumulation_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rx_bytes_total', sa.BigInteger(), nullable=False),
    sa.Column('tx_bytes_total', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['pppoe_clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_accum_client_active', 'accumulation_periods', ['client_id', 'period_end'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_accum_client_active', table_name='accumulation_periods')
    op.drop_table('accumulation_periods')
    op.drop_index('ix_traffic_samples_client_time', table_name='traffic_samples')
    op.drop_table('traffic_samples')
    # ### end Alembic commands ###
