"""add pppoe_clients and session_state tables

Revision ID: c8aced5619c2
Revises: e664b2806e24
Create Date: 2026-09-23 12:23:38.071024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8aced5619c2'
down_revision: Union[str, None] = 'e664b2806e24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pppoe_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('router_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['router_id'], ['routers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('router_id', 'username', name='uq_client_router_username')
    )
    op.create_index(op.f('ix_pppoe_clients_username'), 'pppoe_clients', ['username'], unique=False)
    op.create_table('session_state',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('last_uptime_seconds', sa.Integer(), nullable=False),
    sa.Column('last_rx_bytes', sa.BigInteger(), nullable=False),
    sa.Column('last_tx_bytes', sa.BigInteger(), nullable=False),
    sa.Column('last_poll_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['pppoe_clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_state')
    op.drop_index(op.f('ix_pppoe_clients_username'), table_name='pppoe_clients')
    op.drop_table('pppoe_clients')
    # ### end Alembic commands ###
